package com.noobk.spmscavenger.experience;

/**
 * GAO-0b — preserved terminal or milestone cause; controls learning sign separately from
 * {@link OutcomeClass}.
 */
public enum ExperienceCause {
    UNSPECIFIED,
    MINING_BLOCK_REMOVED,
    MINING_STAIR_STEP,
    MINING_HANDOFF,
    MINING_CAVE_FOUND,
    MINING_TUNNEL_HANDOFF,
    MINING_NO_PROGRESS,
    MINING_BUDGET_EXHAUSTED,
    MINING_HAZARD,
    MINING_COMBAT,
    MINING_PLAYER_ORDER,
    MINING_LEASE_EXPIRED,
    EXPOSURE_ORE_TAKEN,
    EXPOSURE_VEIN_IDLE,
    EXPEDITION_UNLOCKED,
    EXPEDITION_STAGE,
    SOCIAL_COMPANION_INVITE,
    RESOURCE_HARVESTED,
    REST_SESSION_OPEN,
    REST_SESSION_CLOSE,
    REST_COMBAT,
    REST_MANDATORY_WORK,
    REST_LEFT_RADIUS,
    SOCIAL_GREET,
    SOCIAL_FOLLOW,
    BOREDOM_THRESHOLD,
    SIMULATION_FRONTIER,
    PROTECTED_INTERRUPT,
    AUTHORITY_CANCEL,
    ENVIRONMENT_BLOCKED
}
